# Generated by Django 3.0.1 on 2020-01-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Wishlist',
        ),
    ]
